import { decryptSecret } from "@docstore/api/services/crypto.service";
import { generateReminders } from "@docstore/api/services/reminder.service";
import {
	loadServerConfig,
	syncManagedIntakeSources,
} from "@docstore/api/services/server-config.service";
import { auth } from "@docstore/auth";
import { db } from "@docstore/db";
import { repairSeedRules, seedIfEmpty } from "@docstore/db/seed";
import { env } from "@docstore/env/server";
import type { IngestionBinding, IngestionContext } from "@docstore/ingestion";
import {
	createIngestionContext,
	createQueue,
	emitEvent,
	type IngestionWorker,
	purgeIntakeLogs,
	purgeRuleRuns,
	startWorker,
	sweepSensitiveShareLinks,
} from "@docstore/ingestion";
import { deriveStorageMasterKey } from "@docstore/storage";
import { createApp } from "./app";

/**
 * Ingestion pipeline (SPEC §5).
 *
 * External binaries (tesseract, poppler) may be missing on a machine: the
 * server starts anyway, without ingestion, and `/health` reports it.
 */
async function startIngestion(): Promise<IngestionBinding | undefined> {
	try {
		const queue = createQueue({ connectionString: env.DATABASE_URL });
		// The context references itself in the injected hooks: the variable is
		// filled in right after it is built.
		let self: IngestionContext | undefined;
		const ctx = createIngestionContext({
			db,
			storagePath: env.STORAGE_PATH,
			tools: {
				tesseractPath: env.TESSERACT_PATH,
				tessdataPrefix: env.TESSDATA_PREFIX,
				popplerPath: env.POPPLER_PATH,
			},
			queue,
			// Reminder recomputation lives in `@docstore/api` (business service):
			// it is injected here so that the `reminders.generate` job can run it
			// without creating an ingestion → api dependency.
			generateReminders: (database) =>
				generateReminders(database, {
					onDueCreated: async (reminders) => {
						if (!self) return;
						for (const item of reminders) {
							await emitEvent(self, "reminder.due", {
								event: "reminder.due",
								reminder: item,
							});
						}
					},
				}),
			// Secret encryption also lives in `@docstore/api`, and the key in
			// `APP_SECRET`: ingestion never reads the environment.
			decryptSecret: (payload) => decryptSecret(payload, env.APP_SECRET),
			// Encryption at rest of sensitive documents (SPEC §8 iteration 7). The
			// master key is derived here, from `APP_SECRET`: rotating that secret
			// is not supported in v1 (see `docs/security.md`).
			encryption: { masterKey: deriveStorageMasterKey(env.APP_SECRET) },
		});
		self = ctx;
		await queue.start();
		const worker = env.WORKER_ENABLED
			? await startWorker(ctx, queue)
			: undefined;
		console.log(
			`[ingestion] queue started${worker ? ` (worker ×${worker.workerIds.length})` : " (worker disabled)"}`,
		);

		// Catches up on the reminders missed since the last shutdown, once the
		// queue is up **and** a worker is listening — published without a
		// consumer the job would sit in `created` and the reminders would stay
		// empty until the 06:00 cron. A failure here must not take the whole
		// pipeline down with it.
		if (worker) {
			try {
				await queue.publishRemindersGenerate();
			} catch (error) {
				console.error("[ingestion] cannot publish reminders.generate", error);
			}
		} else {
			console.warn(
				"[ingestion] worker disabled: reminders will not be generated by this process.",
			);
		}
		return { ctx, queue, worker };
	} catch (error) {
		console.error(
			"[ingestion] cannot start: upload and processing disabled",
			error,
		);
		return undefined;
	}
}

/**
 * Startup taxonomy: default categories and custom fields, inserted only when
 * no category exists yet.
 */
async function seedTaxonomyIfNeeded(): Promise<void> {
	try {
		const result = await seedIfEmpty(db);
		if (result) {
			console.log(
				`[seed] initial taxonomy: ${result.categoriesCreated} category(ies), ${result.customFieldsCreated} field(s), ${result.documentTypesCreated} document type(s), ${result.extractionRulesCreated} extraction(s), ${result.rulesCreated} rule(s), ${result.settingsCreated} setting(s).`,
			);
			return;
		}
		// Already-seeded store: the shipped examples left without any action by
		// the `set_category` removal are refilled (see `repairSeedRules`).
		const repaired = await repairSeedRules(db);
		if (repaired > 0) {
			console.log(`[seed] ${repaired} example automation(s) refilled.`);
		}
	} catch (error) {
		console.error("[seed] cannot seed the taxonomy", error);
	}
}

/**
 * Rule log retention (SPEC §3): runs older than 90 days are deleted on every
 * startup.
 */
async function purgeRuleJournal(): Promise<void> {
	try {
		const deleted = await purgeRuleRuns(db);
		if (deleted > 0) {
			console.log(`[rules] ${deleted} run(s) purged from the log.`);
		}
	} catch (error) {
		console.error("[rules] cannot purge the log", error);
	}
}

/**
 * Intake log retention (30 days), purged on every startup like the rule log.
 */
async function purgeIntakeJournal(): Promise<void> {
	try {
		const deleted = await purgeIntakeLogs(db);
		if (deleted > 0) {
			console.log(`[intake] ${deleted} row(s) purged from the log.`);
		}
	} catch (error) {
		console.error("[intake] cannot purge the log", error);
	}
}

/**
 * Public windows onto sensitive content (SPEC §2), closed at every startup.
 *
 * `0019_revoke-sensitive-share-links` fixes the store once; this runs the same
 * statement on every boot, so a link that slips past the write-time guards is
 * closed by the next restart instead of staying open forever. Idempotent: on a
 * healthy store it revokes nothing and says nothing.
 */
async function sweepSensitiveLinks(): Promise<void> {
	try {
		const revoked = await sweepSensitiveShareLinks(db);
		if (revoked > 0) {
			console.log(
				`[share] ${revoked} public link(s) revoked: they exposed sensitive content.`,
			);
		}
	} catch (error) {
		console.error("[share] cannot sweep the public links", error);
	}
}

/**
 * Server-defined intake sources (`DOCSTORE_CONFIG`).
 *
 * The file owns its rows: they are pushed into `intake_source` at every
 * startup, and the ones whose key disappeared are removed. An unusable file
 * (bad JSON, unknown `${VAR}`, invalid source) stops the server rather than
 * silently running with a configuration nobody asked for.
 */
async function syncServerConfig(): Promise<void> {
	try {
		const loaded = await loadServerConfig({
			path: env.DOCSTORE_CONFIG,
			inboxPath: env.INBOX_PATH ?? null,
		});
		const summary = await syncManagedIntakeSources(db, loaded.config);
		const declared = loaded.config.intakeSources.length;
		if (declared > 0 || summary.deleted > 0) {
			console.log(
				`[config] ${loaded.path}${loaded.exists ? "" : " (absent)"}: ${declared} server-defined source(s) — ${summary.created} created, ${summary.updated} updated, ${summary.unchanged} unchanged, ${summary.deleted} removed.`,
			);
		}
	} catch (error) {
		console.error(
			`[config] invalid server configuration: ${error instanceof Error ? error.message : String(error)}`,
		);
		process.exit(1);
	}
}

await seedTaxonomyIfNeeded();
await syncServerConfig();
await sweepSensitiveLinks();
await purgeRuleJournal();
await purgeIntakeJournal();

const ingestion = await startIngestion();
let worker: IngestionWorker | undefined = ingestion?.worker;

const app = createApp({
	db,
	auth,
	ingestion,
	corsOrigin: env.CORS_ORIGIN,
	appSecret: env.APP_SECRET,
});

let shuttingDown = false;

/** Graceful shutdown: running jobs are allowed to finish. */
async function shutdown(signal: string): Promise<void> {
	if (shuttingDown) return;
	shuttingDown = true;
	console.log(`[server] shutting down (${signal})…`);
	try {
		await worker?.stop();
		worker = undefined;
		await ingestion?.queue?.stop();
	} catch (error) {
		console.error("[server] error during shutdown", error);
	}
	process.exit(0);
}

process.on("SIGTERM", () => void shutdown("SIGTERM"));
process.on("SIGINT", () => void shutdown("SIGINT"));

export { apiHandler, rpcHandler } from "./app";
export { app };

export default {
	// `PORT` lets several worktrees run side by side: `scripts/dev.ts` picks a
	// free port and hands it over, along with the matching `API_PROXY_TARGET`
	// for the web dev server.
	port: Number(process.env.PORT) || 3000,
	fetch: app.fetch,
};
