/**
 * Applies the Drizzle migrations before the API starts.
 * Copied into the image at `/app/packages/db/migrate.mjs`, right next to the
 * `src/migrations` folder generated by `drizzle-kit generate`.
 */
import { fileURLToPath } from "node:url";
import { drizzle } from "drizzle-orm/node-postgres";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import { Pool } from "pg";

// biome-ignore lint/suspicious/noUndeclaredEnvVars: provided by docker compose (docker/.env)
const connectionString = process.env.DATABASE_URL;
if (!connectionString) {
	console.error("[migrate] DATABASE_URL is missing from the environment.");
	process.exit(1);
}

const migrationsFolder = fileURLToPath(
	new URL("./src/migrations", import.meta.url),
);

const MAX_ATTEMPTS = 10;
const RETRY_DELAY_MS = 3000;

const pool = new Pool({ connectionString, max: 1 });

let lastError;
for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
	try {
		await migrate(drizzle(pool), { migrationsFolder });
		console.log("[migrate] migrations applied.");
		await pool.end();
		process.exit(0);
	} catch (error) {
		lastError = error;
		console.warn(
			`[migrate] attempt ${attempt}/${MAX_ATTEMPTS} failed: ${error instanceof Error ? error.message : String(error)}`,
		);
		if (attempt < MAX_ATTEMPTS) {
			await new Promise((resolve) => setTimeout(resolve, RETRY_DELAY_MS));
		}
	}
}

console.error("[migrate] could not apply the migrations.", lastError);
await pool.end().catch(() => {});
process.exit(1);
