import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

/**
 * Keeps `packages/shared/src/version.ts` in step with the root `package.json`.
 *
 * The version has a single home — the root manifest — but it has to be
 * readable from a browser bundle too, where no manifest can be imported. So it
 * is projected into a plain TypeScript constant that every package (front end,
 * API, MCP) imports through `@docstore/shared/settings`.
 *
 * The generated file is committed so that `check-types` and a bare
 * `turbo run build` work on a fresh clone; it is regenerated by `bun run dev`
 * and by `bun run build`, which is what the Docker image runs.
 */

const root = dirname(import.meta.dir);
const manifestPath = join(root, "package.json");
const targetPath = join(root, "packages", "shared", "src", "version.ts");

const manifest = JSON.parse(readFileSync(manifestPath, "utf8")) as {
	version?: string;
};
// A build may stamp another version (Docker `ARG APP_VERSION`); the root
// manifest is the default and the only value the repository tracks.
const version = process.env.APP_VERSION?.trim() || manifest.version?.trim();
if (!version) {
	throw new Error(`"version" is missing from ${manifestPath}.`);
}

const contents = `/**
 * Generated by \`scripts/sync-version.ts\` from the root \`package.json\`.
 * Do not edit by hand: bump the manifest, then run \`bun run sync-version\`.
 */
export const APP_VERSION = ${JSON.stringify(version)};
`;

const current = (() => {
	try {
		return readFileSync(targetPath, "utf8");
	} catch {
		return null;
	}
})();

if (current === contents) {
	console.log(
		`[version] packages/shared/src/version.ts already at ${version}.`,
	);
} else {
	writeFileSync(targetPath, contents, "utf8");
	console.log(`[version] packages/shared/src/version.ts set to ${version}.`);
}
